# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formular.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeinFormular(object):
    def setupUi(self, MeinFormular):
        MeinFormular.setObjectName("MeinFormular")
        MeinFormular.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MeinFormular)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        MeinFormular.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MeinFormular)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Datei = QtWidgets.QMenu(self.menubar)
        self.menu_Datei.setObjectName("menu_Datei")
        self.menu_Hilfe = QtWidgets.QMenu(self.menubar)
        self.menu_Hilfe.setObjectName("menu_Hilfe")
        MeinFormular.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MeinFormular)
        self.statusbar.setObjectName("statusbar")
        MeinFormular.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MeinFormular)
        self.toolBar.setObjectName("toolBar")
        MeinFormular.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Beenden = QtWidgets.QAction(MeinFormular)
        self.action_Beenden.setObjectName("action_Beenden")
        self.action_Neu = QtWidgets.QAction(MeinFormular)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/bilder/dateiNeu.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Neu.setIcon(icon)
        self.action_Neu.setObjectName("action_Neu")
        self.action_ffnen = QtWidgets.QAction(MeinFormular)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/bilder/dateiOeffnen.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ffnen.setIcon(icon1)
        self.action_ffnen.setObjectName("action_ffnen")
        self.action_Speichern = QtWidgets.QAction(MeinFormular)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/bilder/dateiSpeichern.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Speichern.setIcon(icon2)
        self.action_Speichern.setObjectName("action_Speichern")
        self.action_Info = QtWidgets.QAction(MeinFormular)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/bilder/info.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Info.setIcon(icon3)
        self.action_Info.setObjectName("action_Info")
        self.actionSpeichern_unter = QtWidgets.QAction(MeinFormular)
        self.actionSpeichern_unter.setObjectName("actionSpeichern_unter")
        self.menu_Datei.addAction(self.action_Neu)
        self.menu_Datei.addAction(self.action_ffnen)
        self.menu_Datei.addAction(self.action_Speichern)
        self.menu_Datei.addSeparator()
        self.menu_Datei.addAction(self.action_Beenden)
        self.menu_Datei.addAction(self.actionSpeichern_unter)
        self.menu_Hilfe.addAction(self.action_Info)
        self.menubar.addAction(self.menu_Datei.menuAction())
        self.menubar.addAction(self.menu_Hilfe.menuAction())
        self.toolBar.addAction(self.action_Neu)
        self.toolBar.addAction(self.action_ffnen)
        self.toolBar.addAction(self.action_Speichern)
        self.toolBar.addAction(self.action_Info)

        self.retranslateUi(MeinFormular)
        QtCore.QMetaObject.connectSlotsByName(MeinFormular)

    def retranslateUi(self, MeinFormular):
        _translate = QtCore.QCoreApplication.translate
        MeinFormular.setWindowTitle(_translate("MeinFormular", "MiniText"))
        self.menu_Datei.setTitle(_translate("MeinFormular", "&Datei"))
        self.menu_Hilfe.setTitle(_translate("MeinFormular", "&Hilfe"))
        self.toolBar.setWindowTitle(_translate("MeinFormular", "toolBar"))
        self.action_Beenden.setText(_translate("MeinFormular", "&Beenden"))
        self.action_Beenden.setShortcut(_translate("MeinFormular", "Ctrl+B"))
        self.action_Neu.setText(_translate("MeinFormular", "&Neu"))
        self.action_ffnen.setText(_translate("MeinFormular", "Ö&ffnen"))
        self.action_Speichern.setText(_translate("MeinFormular", "&Speichern"))
        self.action_Info.setText(_translate("MeinFormular", "&Info"))
        self.actionSpeichern_unter.setText(_translate("MeinFormular", "Speichern &unter"))
import icons_rc
